

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="images/favicon.ico">

    <title>Global Shopping</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/carousel.css" rel="stylesheet">

<style>
input.required:before{
    content:"*";
    font-weight:bold;
  }
.cover{
  
  background-color: #dce4ed;
  
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;

}
.cover11{
  
  background: url('images/header.jpg') no-repeat ;
  height:100px;
  width:100%;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;

}

@media (min-width: 1100.00px) {
  .cont2  {
    width: 100%;
    padding-right: 60px;
    padding-left: 60px;
    margin-right: auto;
    margin-left: auto
  }
}
@media  (min-width:200.98px) and (max-width: 767.98px) 
{
.widths
{ 
  width: 80%;
    padding: 0px 6px;
}
}
@media  (max-width: 200px) 
{
.widths
{ 
  width: 100%;
    padding-right: 0px;
    padding-left: 0px;
    margin-right: 0;
    margin-left: 0;
}
}

.starter-template {
  padding: 3rem 1.5rem;
  text-align: center;
}

.required .control-label:before {
  content:"*";
  color:red;
  font-weight: 800;
  
}
 
#quantity::-webkit-inner-spin-button,
#quantity::-webkit-outer-spin-button {
    opacity: 1;
    -webkit-appearance: auto;
}


.footer{

      width: 85%;
      margin: auto;

}
.padd {
    padding-top: 35px;
    padding-bottom: 15px;
    
   
}
.social-icons-wrap
{
margin-top:5px;
margin-bottom:10px;
margin-right:3px;
margin-left:12px;
}
.sub-btn button {
    padding: 8px 40px;
    font-size: 20px;
    background-color: #7c8ff5 !important;
    border: 1px #7c8ff5;
    border-radius: 2px;
}
.required-field span {
    color: #FF0000;
    font-size: 18px;
    width: 90%;
    display: block;
    margin: 0 auto;
}


.header{
	
	margin-bottom: 0px !important;
	padding:8px  25px 10px 25px;
}
.header .company-logo h2{
	color: #fff;
}
.header .company-top h1 {
	color: #fff;
	text-align: center;
	
	font-weight: 500;
  margin-bottom: 0px;
  margin-top: 3px;
} 
.header .company-top h5 {
	color: #fff;
	text-align: center;
	font-size: 20px;
  font-weight: bold;
  margin-top: 3px;
} 
.header .company-link h6 {
	color: #fff;
	text-align: right;
	padding-top: 14px;
	font-weight: 500;
	font-size: 24px;

  margin-top: 3px;
  position: relative;
    min-height: 1px;
    padding-left: 10px;
    padding-right: 10px;
}
.header img {
    width: 220px;
    max-width:100%;
    height:auto;
}

@media (max-width: 767px){
.header img {
    width: 122px;
}
.header .company-top h1 {
		font-size: 21px;
	}
	.header .company-top h5 {
		font-size: 14px;
	}
	.header .company-link h6 {
		font-size: 16px;
		padding-top: 0px;
		margin-bottom: 0px;
  }
  .row-product .cancel{
		right: -10px;
	}
}
@media (max-width: 490px){
.header img {
    width: 80px;}
    .header .company-top h1 {
		font-size: 14px;
	}
	.header .company-top h5,
	.header .company-link h6 {
		font-size: 14px;
	}
	.company-logo,
	.company-link h6{
		text-align: center !important;
	}
}
@media (max-width: 1200px){
.logo{
    width: 80%;
}
}
.row-product .cancel {
	background: #2962ff !important;
	color: #fff;
	padding-top:10px;
  margin-top: 5px;
	width: 30px;
	height: 30px;
	line-height: 9px;
	font-size: 14px;
	font-weight: 700;
	text-align: center;
	cursor: pointer;
	border-radius: 2px;
}
@media (max-width: 767px)
{
.row-product .cancel {
  position: absolute;
  right: 10px;
  background: #2962ff !important;
	color: #fff;
	padding: 3px;
	width: 15px;
	height: 15px;
	line-height: 9px;
	font-size: 9px;
	font-weight: 700;
	text-align: center;
  cursor: pointer;
  margin-top:50px;

	border-radius: 2px;
}
}

a:hover {
    text-decoration: none
}

.calc{
    font-size: 18px;
    font-weight:600;
}
.calcs{
    /* font-size: 18px; */
    font-weight:600;
}

.calcsrow{
    font-size: 25px;
    font-weight:600;
    border: none;
    width: 80%;
    /* border:magenta 2px solid; */
}
.tots{
color: dodgerblue;
font-size: 2rem;
font-weight: bolder;
}
#price1,#quantity1,#weight{
    font-weight: 600;
    color: black;
    width: 90%
}
.calcy{
    font-size: 28px;
    font-weight:600;
}
.calcinput1{background: url(images/g.png) no-repeat scroll 0px 0px;
padding-left:30px;
text-align: center;
}
.calcinput2{background: url(images/quantity.png) no-repeat scroll 0px 0px;
padding-left:30px;
text-align: center;
}
.calcinput3{background: url(images/weight.png) no-repeat scroll 0px 0px;
padding-left:30px;
text-align: center;
}	


        * {
            box-sizing: border-box;
        }
        
        input[type=number], select, textarea {
            /* width: 95%; */
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            resize: vertical;
        }
        
        label {
            padding: 12px 12px 12px 0;
            display: inline-block;
        }
        
        input[type=submit] {
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        
        input[type=submit]:hover {
            background-color: #45a049;
        }
        
        .container {
            border-radius: 5px;
            background-color: white;
            
        }
        
        .col-25 {
            float: left;
            width: 20%;
            margin-top: 6px;
        }
        
        .col-75 {
            float: left;
            width: 75%;
            margin-top: 6px;
        }
        .col-90 {
            float: left;
            width: 90%;
            margin-top: 6px;
        }
        .col-10 {
            float: left;
            width: 10%;
            margin-top: 6px;
        }
        .col-50 {
            float: left;
            /* width: 50%; */
            margin-top: 6px;
        }
        .col-70 {
            float: left;
            width: 70%;
            margin-top: 6px;
        }
        .col-30 {
            float: left;
            width: 30%;
            margin-top: 6px;
        }
        
        .col-100 {
            float: left;
            width: 100%;
            margin-top: 6px;
        }
      
        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }
        
        /* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
        @media screen and (max-width: 600px) {
           .col-25,.col-30, .col-50, .col-70,.col-75,.col-100, input[type=submit] {
                /* width: 100%; */
                margin-top: 0;
            }
        }
        .table td, .table th {
    padding: .75rem;
    vertical-align: top;
    border-top: none;
        }
        
#price1::-webkit-outer-spin-button,
#price1::-webkit-inner-spin-button,
#quantity1::-webkit-inner-spin-button,
#quantity1::-webkit-outer-spin-button,
#weight::-webkit-inner-spin-button,
#weight::-webkit-outer-spin-button {
    /* display: none; <- Crashes Chrome on hover */
    -webkit-appearance:none;
    opacity: 0;
    margin: 0; 
    /* <-- Apparently some margin are still there even though it's hidden */
}
        </style>
  </head>

  <body >
    <h1>Thank You</h1>
  </body>
      </html>
      